version: '2'
services:
  www:
    container_name: wbo
    volumes:
      - server-data:/home/node/app/server-data
    ports:
      - '127.0.0.1:8080:8080' # to use with reverse proxy
      # - 80:8080 to publish direct
    build:
      context: .
    restart: always
